# QuietCool Smart Attic Fan Control Configuration
# This configuration file enables control of a QuietCool Smart Attic Fan Control via ESPHome
# It provides BLE connectivity, fan speed control, timer functionality, and sensor monitoring

# Core Configuration
# ----------------------------------------
# Define BLE service and characteristic UUIDs used for communication with the fan
substitutions:
  service_uuid: "000000ff-0000-1000-8000-00805f9b34fb"
  characteristic_uuid: "0000ff01-0000-1000-8000-00805f9b34fb"
  mac_address: "00:00:00:00:00:00"

# Basic ESPHome device configuration
esphome:
  name: quietcool-fan
  friendly_name: QuietCool Fan
  name_add_mac_suffix: true

# Hardware configuration for ESP32 development board
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API integration
api:

# Enable Over-The-Air updates
ota:
  - platform: esphome

# Enable captive portal for initial WiFi setup
captive_portal:

# WiFi configuration with fallback access point
wifi:
  ap:

# BLE configuration for connecting to the QuietCool fan
# Uses passive scanning to preserve battery life
esp32_ble_tracker:
  scan_parameters:
    active: false

# BLE client configuration for maintaining connection with the fan
# Automatically connects and sends login credentials on connection
ble_client:
  - mac_address: ${mac_address}
    id: qc_ble
    auto_connect: true
    on_connect:
      - delay: 2s
      - script.execute:
          id: send_ble_msg
          msg: !lambda return "{\"A\":13,\"P\":\"" + id(pair_id).state + "\"}";
      - script.wait: send_ble_msg

# Global Variables and Utilities
# ----------------------------------------
# Enable JSON parsing for BLE communication
json:

# Global variable to store BLE messages
globals:
  - id: ble_message
    type: std::string
    initial_value: ""
    restore_value: no

# Configure logging level
logger:
  level: INFO

# Fan Control Scripts
# ----------------------------------------
# Scripts handle different aspects of fan control:
# - set_mode: Changes fan operation mode (Timer/Idle)
# - set_timer: Configures timer duration and speed
# - send_ble_msg: Handles BLE message transmission
script:
  - id: set_mode
    parameters:
      mode: string
    then:
      - script.execute:
          id: send_ble_msg
          msg: !lambda return "{\"A\":9,\"M\":\"" + mode + "\"}";
      - script.wait: send_ble_msg
  - id: set_timer
    parameters:
      hours: int
      minutes: int
      speed: string
    then:
      - script.execute:
          id: send_ble_msg
          msg: !lambda return "{\"A\":7,\"H\":" + std::to_string(hours) + ",\"M\":" + std::to_string(minutes) + ",\"R\":\"" + speed + "\"}";
      - script.wait: send_ble_msg
  - id: send_ble_msg
    parameters:
      msg: string
    mode: queued
    then:
      - ble_client.ble_write:
          id: qc_ble
          service_uuid: ${service_uuid}
          characteristic_uuid: ${characteristic_uuid}
          value: !lambda |-
              ESP_LOGI("quietcool", "Sending BLE message: %s", msg.c_str());
              return std::vector<uint8_t>(msg.begin(), msg.end());
      - delay: 1s

# Fan Component Configuration
# ----------------------------------------
# Template-based fan platform that provides:
# - Two speed levels (LOW/HIGH)
# - Timer-based operation
# - State restoration after power loss
fan:
  - platform: template
    name: "QuietCool Fan"
    id: quietcool_fan
    has_direction: false
    has_oscillating: false
    speed_count: 2
    restore_mode: RESTORE_DEFAULT_OFF
    on_speed_set:
      - logger.log: "Setting speed"
      - script.execute:
          id: set_timer
          speed: !lambda 'return x == 2 ? "HIGH" : "LOW";'
          hours: 3
          minutes: 0
      - script.wait: set_timer
      - script.execute:
          id: set_mode
          mode: "Timer"
      - script.wait: set_mode
    on_turn_on:
      - logger.log: "Turning on timer"
      - script.execute:
          id: set_mode
          mode: "Timer"
      - script.wait: set_mode
      - event.trigger:
          id: fan_on_event
          event_type: fan_on
    on_turn_off:
      - logger.log: "Turning off"
      - script.execute:
          id: set_mode
          mode: "Idle"
      - script.wait: set_mode
      - event.trigger:
          id: fan_off_event
          event_type: fan_off

# Timer Controls
# ----------------------------------------
# Provides user-adjustable timer settings:
# - Hours (0-23)
# - Minutes (0-59)
# Updates are sent to the fan immediately when values change
number:
  - platform: template
    name: "Timer Hours"
    id: timer_hours
    min_value: 0
    max_value: 23
    step: 1
    unit_of_measurement: "h"
    device_class: duration
    optimistic: true
    initial_value: 3
    on_value:
      - script.execute:
          id: set_timer
          hours: !lambda return x;
          minutes: !lambda return id(timer_minutes).state;
          speed: &set_timer_speed !lambda 'return id(quietcool_fan).speed == 2 ? "HIGH" : "LOW";'

  - platform: template
    name: "Timer Minutes"
    id: timer_minutes
    min_value: 0
    max_value: 59
    step: 1
    unit_of_measurement: "m"
    device_class: duration
    optimistic: true
    initial_value: 0
    on_value:
      - script.execute:
          id: set_timer
          hours: !lambda return id(timer_hours).state;
          minutes: !lambda return x;
          speed: *set_timer_speed

# Device Configuration
# ----------------------------------------
# Stores device pairing ID and provides pairing button
# The pair ID is a 16-character hex string used for device authentication
text:
  - id: pair_id
    name: "Pair ID"
    platform: template
    mode: text
    min_length: 10
    max_length: 16
    optimistic: true
    initial_value: "a1b2c1d2a2b1c2d1"
    restore_value: true

button:
  - platform: template
    name: "Pair BLE"
    id: pair_button
    on_press:
      then:
        - script.execute:
            id: send_ble_msg
            msg: !lambda return "{\"A\":14,\"P\":\"" + id(pair_id).state + "\"}";
        - script.wait: send_ble_msg

# Sensor Templates and Configurations
# ----------------------------------------
# Define reusable sensor templates for temperature and humidity
# These sensors receive data from the fan's built-in sensors
.humidity_sensor: &humidity_sensor
  platform: template
  unit_of_measurement: "%"
  device_class: humidity
  state_class: measurement

.temperature_sensor: &temperature_sensor
  platform: template
  unit_of_measurement: "°F"
  device_class: temperature
  state_class: measurement

sensor:
  - <<: *humidity_sensor
    name: humidity
    id: humidity
  - <<: *temperature_sensor
    name: temperature
    id: temperature
  - <<: *temperature_sensor
    name: temp_sample
    id: temp_sample
  - <<: *humidity_sensor
    name: humidity_sample
    id: humidity_sample
  - <<: *temperature_sensor
    name: get_temp_h
    id: get_temp_h
    disabled_by_default: true
  - <<: *humidity_sensor
    name: get_hum_h
    id: get_hum_h
    disabled_by_default: true
  - <<: *temperature_sensor
    name: get_temp_l
    id: get_temp_l
    disabled_by_default: true
  - <<: *humidity_sensor
    name: get_hum_l
    id: get_hum_l
    disabled_by_default: true
  - platform: template
    name: get_hour
    id: get_hour
    unit_of_measurement: "h"
    device_class: duration
    accuracy_decimals: 0
    disabled_by_default: true
  - platform: template
    name: get_minute
    id: get_minute
    unit_of_measurement: "m"
    device_class: duration
    accuracy_decimals: 0
    disabled_by_default: true

# Text Sensors and BLE Data Handling
# ----------------------------------------
# Various text sensors for monitoring fan state and settings
# The BLE data handler parses incoming JSON messages and updates appropriate sensors
text_sensor:
  - platform: template
    name: mode
    id: mode
  - platform: template
    name: range
    id: range
  - platform: template
    name: fan_type
    id: fan_type
    disabled_by_default: true
  - platform: template
    name: name
    id: name
    disabled_by_default: true
  - platform: template
    name: model
    id: model
    disabled_by_default: true
  - platform: template
    name: serial_num
    id: serial_num
    disabled_by_default: true
  - platform: template
    name: sensor_state
    id: sensor_state
    disabled_by_default: true
  - platform: template
    name: pair_state
    id: pair_state
  - platform: template
    name: get_hum_range
    id: get_hum_range
    disabled_by_default: true
  - platform: template
    name: get_time_range
    id: get_time_range
    disabled_by_default: true
  - platform: ble_client
    name: "BLE Data"
    id: quietcool_ble_data
    service_uuid: ${service_uuid}
    characteristic_uuid: ${characteristic_uuid}
    notify: true
    internal: true
    on_notify:
      - lambda: |-
            static std::string& accumulated = id(ble_message);
            accumulated += x;
            if (!x.empty() && x.back() == '}') {
              id(quietcool_ble_data).publish_state(accumulated);
              ESP_LOGD("quietcool", "Received JSON data: %s", accumulated.c_str());
              bool parsed = false;
              // substr to remove "QQ" prefix from JSON response
              json::parse_json(accumulated.substr(2), [&parsed](JsonObject root) -> bool {
                parsed = true;
                
                 // Determine API (A) and populate sensors/text sensors accordingly
                int api = 0;
                if (!root["A"].isNull()) {
                  api = root["A"].as<int>();
                }

                for (JsonObject::iterator it = root.begin(); it != root.end(); ++it) {
                  std::string key = it->key().c_str();

                  if (key == "A") {
                    continue; // Already processed API
                  }

                  // GetWorkState
                  if (api == 1) {
                    if (key == "C") { // Control Type but not currently used
                      continue;
                    }
                    if (key == "M") { // Mode
                      id(mode).publish_state(it->value().as<std::string>());
                      continue;
                    }
                    if (key == "R") { // Range
                      id(range).publish_state(it->value().as<std::string>());
                      continue;
                    }
                    if (key == "S") { // Sensor state
                      id(sensor_state).publish_state(it->value().as<std::string>());
                      continue;
                    }
                    if (key == "T") { // Temp sample (example shows 553 -> probably 55.3)
                      float v = it->value().as<float>() / 10.0f;
                      id(temp_sample).publish_state(v);
                      continue;
                    }
                    if (key == "H") { // Humidity sample
                      id(humidity_sample).publish_state(it->value().as<float>());
                      continue;
                    }
                  }

                  // GetParameter
                  if (api == 2) {
                    if (key == "B") { // Mode (sometimes returned as B)
                      id(mode).publish_state(it->value().as<std::string>());
                      continue;
                    }
                    if (key == "C") { // Fan type
                      id(fan_type).publish_state(it->value().as<std::string>());
                      continue;
                    }
                    if (key == "D") { // GetTemp_H
                      float v = it->value().as<float>();
                      if (v != 255.0f) {
                        // 255.0f would mean it's initially 255, which is a special value indicating "not set"
                        v = v / 10.0f;
                      }
                      id(get_temp_h).publish_state(v);
                      continue;
                    }
                    if (key == "F") { // GetTemp_L
                      float v = it->value().as<float>();
                      if (v != 255.0f) {
                        // 255.0f would mean it's initially 255, which is a special value indicating "not set"
                        v = v / 10.0f;
                      }
                      id(get_temp_l).publish_state(v);
                      continue;
                    }
                    if (key == "G") { // GetHum_H
                      id(get_hum_h).publish_state(it->value().as<float>());
                      continue;
                    }
                    if (key == "H") { // GetHum_L
                      id(get_hum_l).publish_state(it->value().as<float>());
                      continue;
                    }
                    if (key == "I") { // GetHum_Range
                      id(get_hum_range).publish_state(it->value().as<std::string>());
                      continue;
                    }
                    if (key == "J") { // GetHour
                      id(get_hour).publish_state(it->value().as<float>());
                      continue;
                    }
                    if (key == "K") { // GetMinute
                      id(get_minute).publish_state(it->value().as<float>());
                      continue;
                    }
                    if (key == "L") { // GetTime_Range
                      id(get_time_range).publish_state(it->value().as<std::string>());
                      continue;
                    }
                    if (key == "M") { // Pair state
                      id(pair_state).publish_state(it->value().as<std::string>());
                      continue;
                    }
                  }

                  // GetFanInfo
                  if (api == 17) {
                    if (key == "N") { // Name
                      id(name).publish_state(it->value().as<std::string>());
                      continue;
                    }
                    if (key == "M") { // Model
                      id(model).publish_state(it->value().as<std::string>());
                      continue;
                    }
                    if (key == "S") { // Serial number
                      id(serial_num).publish_state(it->value().as<std::string>());
                      continue;
                    }
                    if (key == "G") { // GuideSetup but not currently used
                      continue;
                    }
                  }

                  ESP_LOGD("quietcool", "No mapping for API %d key: %s", api, key.c_str());
                }

                return true;
              });
              if (!parsed) {
                ESP_LOGW("quietcool", "Failed to parse JSON: %s", accumulated.c_str());
              }
              accumulated.clear();
            }

# Periodic Updates
# ----------------------------------------
# Polls the fan every 15 seconds for:
# - Current parameters
# - Work state
# - Fan information
# This ensures the Home Assistant interface stays in sync with the actual fan state
interval:
  - interval: 15s
    then:
      - script.execute:
          id: send_ble_msg
          # GetParameter
          msg: !lambda return "{\"A\":2}";
      - script.wait: send_ble_msg
      - delay: 5s
      - script.execute:
          id: send_ble_msg
          # GetWorkState
          msg: !lambda return "{\"A\":1}";
      - script.wait: send_ble_msg
      - delay: 5s
      - script.execute:
          id: send_ble_msg
          # GetFanInfo
          msg: !lambda return "{\"A\":17}";
      - script.wait: send_ble_msg

time:
  - platform: homeassistant
    id: homeassistant_time

event:
  - platform: template
    name: Fan On Event
    id: fan_on_event
    event_types:
      - fan_on
  - platform: template
    name: Fan Off Event
    id: fan_off_event
    event_types:
      - fan_off
